import re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import glob
import os

# plots the heatmaps generated by xB_Q2_scan.cpp

def parse_int(pattern: str, text: str, default: int) -> int:
    m = re.search(pattern, text)
    return int(m.group(1)) if m else default


def parse_float(pattern: str, text: str, default: float) -> float:
    m = re.search(pattern, text)
    return float(m.group(1)) if m else default


def discover_xb_q2_files():
    """Discover all available xB-Q2 histogram files"""
    # Check for organized directory structure first
    script_dir = os.path.dirname(os.path.abspath(__file__))
    # Explicitly add analysis_output/txt_files relative to script_dir
    analysis_txt_dir = os.path.join(script_dir, '..', 'analysis_output', 'txt_files')
    # Also check parent directory (workspace root) for analysis_output/txt_files
    parent_dir = os.path.abspath(os.path.join(script_dir, '..', '..', '..', '..'))
    parent_analysis_txt_dir = os.path.join(parent_dir, 'analysis_output', 'txt_files')
    txt_dir_candidates = [
        analysis_txt_dir,
        parent_analysis_txt_dir,
        script_dir,
        parent_dir
    ]
    print("Searching for input files in these directories:")
    for d in txt_dir_candidates:
        print("  ", d)

    found_files = {'pair': [], 'region': [], 'point': []}
    for d in txt_dir_candidates:
        if os.path.exists(d):
            found_files['pair'] += [os.path.join(d, "hist_xB_Q2_pair1.txt"), os.path.join(d, "hist_xB_Q2_pair2.txt")]
            found_files['region'] += glob.glob(os.path.join(d, "hist_xB_Q2_region*.txt"))
            found_files['point'] += glob.glob(os.path.join(d, "hist_xB_Q2_point*.txt"))

    # Remove duplicates and non-existent files
    found_files['pair'] = [f for f in dict.fromkeys(found_files['pair']) if os.path.exists(f)]
    found_files['region'] = [f for f in dict.fromkeys(found_files['region']) if os.path.exists(f)]
    found_files['point'] = [f for f in dict.fromkeys(found_files['point']) if os.path.exists(f)]
    # Sort region files by region number
    found_files['region'] = sorted(found_files['region'], key=lambda x: int(re.search(r'region(\d+)', x).group(1)) if re.search(r'region(\d+)', x) else 0)
    # Sort point files by point number
    found_files['point'] = sorted(found_files['point'], key=lambda x: int(re.search(r'point(\d+)', x).group(1)) if re.search(r'point(\d+)', x) else 0)

    print("Found files:")
    for k in found_files:
        for f in found_files[k]:
            print(f"  {k}: {f}")
    if not any(found_files.values()):
        print("ERROR: No xB-Q2 histogram files found in analysis_output/txt_files or script directory.")
    return found_files['pair'], found_files['region'], found_files['point']


def get_point_label(path: str) -> str:
    """Extract a meaningful label from the file path"""
    if "pair1" in path:
        return "Star (Pair 1)"
    elif "pair2" in path:
        return "Rocket (Pair 2)"
    elif "region" in path:
        # Extract region number
        match = re.search(r'region(\d+)', path)
        if match:
            region_num = int(match.group(1))
            return f"Region {region_num}"
    elif "point" in path:
        # Extract point number
        match = re.search(r'point(\d+)', path)
        if match:
            point_num = int(match.group(1))
            return f"Point {point_num}"
    return "Unknown"


def extract_target_angles(target_info: str) -> tuple:
    """Extract theta12 and theta23 values from target info string"""
    theta12_match = re.search(r'theta12=([\d.]+)', target_info)
    theta23_match = re.search(r'theta23=([\d.]+)', target_info)
    if theta12_match and theta23_match:
        return float(theta12_match.group(1)), float(theta23_match.group(1))
    return None, None


def get_enhanced_label(path: str, target_info: str) -> str:
    """Get an enhanced label including target angles"""
    base_label = get_point_label(path)
    theta12, theta23 = extract_target_angles(target_info)
    
    if theta12 is not None and theta23 is not None:
        # Special names for known configurations
        if abs(theta12 - 120.0) < 1.0 and abs(theta23 - 120.0) < 1.0:
            return f"Star (θ₁₂={theta12:.0f}°, θ₂₃={theta23:.0f}°)"
        elif abs(theta12 - 180.0) < 1.0 and abs(theta23 - 0.0) < 1.0:
            return f"Rocket (θ₁₂={theta12:.0f}°, θ₂₃={theta23:.0f}°)"
        elif abs(theta12 - 0.0) < 1.0 and abs(theta23 - 180.0) < 1.0:
            return f"(θ₁₂={theta12:.0f}°, θ₂₃={theta23:.0f}°)"
        elif abs(theta12 - 180.0) < 1.0 and abs(theta23 - 180.0) < 1.0:
            return f"(θ₁₂={theta12:.0f}°, θ₂₃={theta23:.0f}°)"
        else:
            return f"{base_label} (θ₁₂={theta12:.0f}°, θ₂₃={theta23:.0f}°)"
    
    return base_label


def load_xb_q2_hist(path: str):
    """Load sparse xB-Q2 histogram from hist_xB_Q2.txt.
    Returns xB centers, Q2 centers, a dense heatmap grid of shape [Q2_index, xB_index],
    and target angle information if available.
    """
    # Read header
    header = ""
    target_info = ""
    with open(path, "r") as f:
        for line in f:
            if line.startswith("#"):
                header += line
                if "Target pair" in line or "point" in line or "region" in line:
                    target_info = line.strip()
            else:
                break

    xB_bins = parse_int(r"xB_bins\s+(\d+)", header, 0)
    Q2_bins = parse_int(r"Q2_bins\s+(\d+)", header, 0)
    xB_min = parse_float(r"xB_min\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)
    xB_max = parse_float(r"xB_max\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)
    Q2_min = parse_float(r"Q2_min\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)
    Q2_max = parse_float(r"Q2_max\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)

    if xB_bins <= 0 or Q2_bins <= 0:
        raise ValueError("Could not parse xB_bins/Q2_bins from header of " + path)

    # Bin widths and centers
    dxB = (xB_max - xB_min) / xB_bins
    dQ2 = (Q2_max - Q2_min) / Q2_bins
    xb_centers = np.linspace(xB_min + dxB / 2.0, xB_max - dxB / 2.0, xB_bins)
    q2_centers = np.linspace(Q2_min + dQ2 / 2.0, Q2_max - dQ2 / 2.0, Q2_bins)

    # Prepare full grid (y: Q2, x: xB)
    heatmap = np.zeros((Q2_bins, xB_bins), dtype=float)

    # Load numeric rows, ignoring comments
    data = np.loadtxt(path, comments="#")
    if data.ndim == 1 and data.size == 0:
        return xb_centers, q2_centers, heatmap, (xB_min, xB_max, Q2_min, Q2_max), target_info

    data = np.atleast_2d(data)
    xb = data[:, 0]
    q2 = data[:, 1]
    w = data[:, 2]

    # Map bin centers back to indices
    ii = np.rint((xb - (xB_min + dxB / 2.0)) / dxB).astype(int)
    jj = np.rint((q2 - (Q2_min + dQ2 / 2.0)) / dQ2).astype(int)
    ii = np.clip(ii, 0, xB_bins - 1)
    jj = np.clip(jj, 0, Q2_bins - 1)
    for x, y, ww in zip(ii, jj, w):
        heatmap[y, x] += ww

    return xb_centers, q2_centers, heatmap, (xB_min, xB_max, Q2_min, Q2_max), target_info
    """Load sparse xB-Q2 histogram from hist_xB_Q2.txt.
    Returns xB centers, Q2 centers, a dense heatmap grid of shape [Q2_index, xB_index],
    and target angle information if available.
    """
    # Read header
    header = ""
    target_info = ""
    with open(path, "r") as f:
        for line in f:
            if line.startswith("#"):
                header += line
                if "Target pair" in line:
                    target_info = line.strip()
            else:
                break

    xB_bins = parse_int(r"xB_bins\s+(\d+)", header, 0)
    Q2_bins = parse_int(r"Q2_bins\s+(\d+)", header, 0)
    xB_min = parse_float(r"xB_min\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)
    xB_max = parse_float(r"xB_max\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)
    Q2_min = parse_float(r"Q2_min\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)
    Q2_max = parse_float(r"Q2_max\s+([-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)", header, 0.0)

    if xB_bins <= 0 or Q2_bins <= 0:
        raise ValueError("Could not parse xB_bins/Q2_bins from header of " + path)

    # Bin widths and centers
    dxB = (xB_max - xB_min) / xB_bins
    dQ2 = (Q2_max - Q2_min) / Q2_bins
    xb_centers = np.linspace(xB_min + dxB / 2.0, xB_max - dxB / 2.0, xB_bins)
    q2_centers = np.linspace(Q2_min + dQ2 / 2.0, Q2_max - dQ2 / 2.0, Q2_bins)

    # Prepare full grid (y: Q2, x: xB)
    heatmap = np.zeros((Q2_bins, xB_bins), dtype=float)

    # Load numeric rows, ignoring comments
    data = np.loadtxt(path, comments="#")
    if data.ndim == 1 and data.size == 0:
        return xb_centers, q2_centers, heatmap, (xB_min, xB_max, Q2_min, Q2_max), target_info

    data = np.atleast_2d(data)
    xb = data[:, 0]
    q2 = data[:, 1]
    w = data[:, 2]

    # Map bin centers back to indices
    ii = np.rint((xb - (xB_min + dxB / 2.0)) / dxB).astype(int)
    jj = np.rint((q2 - (Q2_min + dQ2 / 2.0)) / dQ2).astype(int)
    ii = np.clip(ii, 0, xB_bins - 1)
    jj = np.clip(jj, 0, Q2_bins - 1)
    for x, y, ww in zip(ii, jj, w):
        heatmap[y, x] += ww

    return xb_centers, q2_centers, heatmap, (xB_min, xB_max, Q2_min, Q2_max), target_info


def main():
    # Configuration: Set to True for cropped view around non-zero values, False for full data range
    crop_to_nonzero = True

    # Set global font sizes for matplotlib
    import matplotlib
    matplotlib.rcParams.update({
        'font.size': 12,           # Default font size
        'axes.titlesize': 16,      # Title font size
        'axes.labelsize': 14,      # Axis label font size
        'xtick.labelsize': 12,     # X-axis tick label font size
        'ytick.labelsize': 12,     # Y-axis tick label font size
        'legend.fontsize': 12,     # Legend font size
    })

    # Make script_dir and parent_dir available for PNG saving
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.abspath(os.path.join(script_dir, '..', '..', '..', '..'))
    
    # Discover all available histogram files
    pair_files, region_files, point_files = discover_xb_q2_files()
    
    # Check which files actually exist
    valid_pair_files = [f for f in pair_files if os.path.exists(f)]
    valid_region_files = [f for f in region_files if os.path.exists(f)]
    valid_point_files = [f for f in point_files if os.path.exists(f)]
    
    # Combine all valid files, prioritizing region files over point files over pair files
    all_files = valid_region_files if valid_region_files else (valid_point_files if valid_point_files else valid_pair_files)
    
    if not all_files:
        print("No valid xB-Q2 histogram files found.")
        print("Expected files: hist_xB_Q2_region*.txt or hist_xB_Q2_point*.txt or hist_xB_Q2_pair1.txt, hist_xB_Q2_pair2.txt")
        print("Run the C++ xB_Q2_scan program first to generate them.")
        return
    
    print(f"Found {len(all_files)} xB-Q2 histogram files:")
    for f in all_files:
        print(f"  {f}")
    
    # Load all valid data first to determine global ranges
    valid_data = []
    all_xb_ranges = []
    all_q2_ranges = []
    
    for i, path in enumerate(all_files):
        try:
            data = load_xb_q2_hist(path)
            valid_data.append((i, path, data))
            
            # Extract range info for global calculation
            xb_c, q2_c, heatmap, (xB_min, xB_max, Q2_min, Q2_max), target_info = data
            
            if crop_to_nonzero:
                # Find non-zero data ranges for this histogram
                total = np.sum(heatmap)
                if total > 0:
                    heatmap_norm = heatmap / total
                    nonzero_indices = np.where(heatmap_norm > 0)
                    if len(nonzero_indices[0]) > 0:
                        q2_indices = nonzero_indices[0]  # row indices (Q2)
                        xb_indices = nonzero_indices[1]  # col indices (xB)
                        
                        # Calculate actual data ranges with padding
                        xb_idx_min = max(0, xb_indices.min() - 2)
                        xb_idx_max = min(len(xb_c) - 1, xb_indices.max() + 2)
                        q2_idx_min = max(0, q2_indices.min() - 2)
                        q2_idx_max = min(len(q2_c) - 1, q2_indices.max() + 2)
                        
                        dxB = (xB_max - xB_min) / len(xb_c)
                        dQ2 = (Q2_max - Q2_min) / len(q2_c)
                        xb_min_data = xb_c[xb_idx_min] - dxB/2
                        xb_max_data = xb_c[xb_idx_max] + dxB/2
                        q2_min_data = q2_c[q2_idx_min] - dQ2/2
                        q2_max_data = q2_c[q2_idx_max] + dQ2/2
                        
                        all_xb_ranges.append((xb_min_data, xb_max_data))
                        all_q2_ranges.append((q2_min_data, q2_max_data))
                    else:
                        # No non-zero data, use full range
                        all_xb_ranges.append((xB_min, xB_max))
                        all_q2_ranges.append((Q2_min, Q2_max))
                else:
                    # No data, use full range
                    all_xb_ranges.append((xB_min, xB_max))
                    all_q2_ranges.append((Q2_min, Q2_max))
            else:
                # Use full range
                all_xb_ranges.append((xB_min, xB_max))
                all_q2_ranges.append((Q2_min, Q2_max))
                
        except Exception as e:
            print(f"Error loading {path}: {e}. Skipping...")
            continue
    
    if len(valid_data) == 0:
        print("No valid histogram data could be loaded.")
        return
    
    # Calculate global ranges from all histograms
    if all_xb_ranges and all_q2_ranges:
        global_xb_min = min(r[0] for r in all_xb_ranges)
        global_xb_max = max(r[1] for r in all_xb_ranges)
        global_q2_min = min(r[0] for r in all_q2_ranges)
        global_q2_max = max(r[1] for r in all_q2_ranges)
        
        print(f"Global xB range: [{global_xb_min:.3f}, {global_xb_max:.3f}]")
        print(f"Global Q2 range: [{global_q2_min:.3f}, {global_q2_max:.3f}]")
    else:
        # Fallback to first histogram's full range
        _, _, _, (xB_min, xB_max, Q2_min, Q2_max), _ = valid_data[0][2]
        global_xb_min, global_xb_max = xB_min, xB_max
        global_q2_min, global_q2_max = Q2_min, Q2_max
    
    # Determine subplot layout
    n_plots = len(valid_data)
    if n_plots == 1:
        fig, ax = plt.subplots(figsize=(10, 8))
        axes = [ax]
    elif n_plots == 2:
        fig, axes = plt.subplots(1, 2, figsize=(16, 8))
    elif n_plots <= 4:
        fig, axes = plt.subplots(2, 2, figsize=(16, 12))
        axes = axes.flatten()
    elif n_plots <= 6:
        fig, axes = plt.subplots(2, 3, figsize=(18, 12))
        axes = axes.flatten()
    elif n_plots <= 9:
        fig, axes = plt.subplots(3, 3, figsize=(18, 15))
        axes = axes.flatten()
    else:
        # For more than 9 plots, create a larger grid
        cols = int(np.ceil(np.sqrt(n_plots)))
        rows = int(np.ceil(n_plots / cols))
        fig, axes = plt.subplots(rows, cols, figsize=(6*cols, 5*rows))
        axes = axes.flatten() if n_plots > 1 else [axes]
    
    # Plot each histogram using global ranges
    for plot_idx, (i, path, (xb_c, q2_c, heatmap, (xB_min, xB_max, Q2_min, Q2_max), target_info)) in enumerate(valid_data):
        # Normalize
        total = np.sum(heatmap)
        heatmap_norm = heatmap / total if total > 0 else heatmap

        if crop_to_nonzero and total > 0:
            # Calculate crop indices based on global ranges to ensure consistency
            dxB = (xB_max - xB_min) / len(xb_c)
            dQ2 = (Q2_max - Q2_min) / len(q2_c)
            
            # Find indices corresponding to global ranges
            xb_idx_min = max(0, int((global_xb_min - (xB_min + dxB/2)) / dxB))
            xb_idx_max = min(len(xb_c) - 1, int((global_xb_max - (xB_min + dxB/2)) / dxB))
            q2_idx_min = max(0, int((global_q2_min - (Q2_min + dQ2/2)) / dQ2))
            q2_idx_max = min(len(q2_c) - 1, int((global_q2_max - (Q2_min + dQ2/2)) / dQ2))
            
            # Crop the heatmap to the global region
            if xb_idx_max > xb_idx_min and q2_idx_max > q2_idx_min:
                heatmap_cropped = heatmap_norm[q2_idx_min:q2_idx_max+1, xb_idx_min:xb_idx_max+1]
            else:
                heatmap_cropped = heatmap_norm
            
            heatmap_to_plot = heatmap_cropped
            # Use global ranges for all plots
            xb_min_plot, xb_max_plot = global_xb_min, global_xb_max
            q2_min_plot, q2_max_plot = global_q2_min, global_q2_max
        else:
            # Use original full data range (global)
            heatmap_to_plot = heatmap_norm
            xb_min_plot, xb_max_plot = global_xb_min, global_xb_max
            q2_min_plot, q2_max_plot = global_q2_min, global_q2_max

        # Plot
        ax = axes[plot_idx]
        
        # Only use LogNorm if there are non-zero values
        if np.any(heatmap_to_plot > 0):
            im = ax.imshow(
                heatmap_to_plot,
                origin="lower",
                extent=[xb_min_plot, xb_max_plot, q2_min_plot, q2_max_plot],
                aspect="auto",
                cmap="viridis",
                norm=LogNorm(vmin=np.min(heatmap_to_plot[heatmap_to_plot > 0]))
            )
        else:
            im = ax.imshow(
                heatmap_to_plot,
                origin="lower",
                extent=[xb_min_plot, xb_max_plot, q2_min_plot, q2_max_plot],
                aspect="auto",
                cmap="viridis"
            )
        
        ax.set_xlabel(r'$x_B$', fontsize=14)
        ax.set_ylabel(r'$Q^2$ (GeV$^2$)', fontsize=14)
        
        # Get enhanced label
        enhanced_label = get_enhanced_label(path, target_info)
        ax.set_title(enhanced_label, fontsize=16)
        
        # Add colorbar to each subplot
        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label('Normalized weight', fontsize=12)
        cbar.ax.tick_params(labelsize=10)
    
    # Hide any unused subplots
    for idx in range(len(valid_data), len(axes)):
        axes[idx].set_visible(False)
    
    plt.tight_layout()
    
    # Save PNG in analysis_output/png_files (relative to script and workspace root)
    analysis_png_dir = os.path.join(script_dir, '..', 'analysis_output', 'png_files')
    parent_dir = os.path.abspath(os.path.join(script_dir, '..', '..', '..', '..'))
    parent_analysis_png_dir = os.path.join(parent_dir, 'analysis_output', 'png_files')
    png_dir_candidates = [
        analysis_png_dir,
        parent_analysis_png_dir,
        script_dir,
        parent_dir
    ]
    png_dir = None
    for d in png_dir_candidates:
        if os.path.exists(d):
            png_dir = d
            break
    if png_dir is None:
        # Try to create the preferred output directory
        try:
            png_dir = png_dir_candidates[0]
            os.makedirs(png_dir, exist_ok=True)
        except Exception:
            png_dir = script_dir
    # Create output filename based on what we plotted
    if valid_region_files:
        output_filename = os.path.join(png_dir, f"xB_Q2_heatmap_all_{len(valid_data)}regions.png")
    elif valid_point_files:
        output_filename = os.path.join(png_dir, f"xB_Q2_heatmap_all_{len(valid_data)}points.png")
    else:
        output_filename = os.path.join(png_dir, f"xB_Q2_heatmap_{len(valid_data)}pairs.png")
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    print(f"Heatmap saved as {output_filename}")
    print(f"All plots use synchronized axis ranges: xB=[{global_xb_min:.3f}, {global_xb_max:.3f}], Q2=[{global_q2_min:.3f}, {global_q2_max:.3f}]")
    plt.show()


if __name__ == "__main__":
    main()
