#!/usr/bin/env python3
"""
Plot 3N/2N ratio as a function of xB
Reads the output file generated by SRC_analysis_3N.cpp
"""

import matplotlib.pyplot as plt
import numpy as np
import os

# Boolean flag to control logarithmic scale
use_log_scale = False

def plot_3N_2N_ratio():
    """Read and plot the 3N/2N ratio data"""
    
    # Output file path
    output_file = "analysis_output/txt_files/3N_2N_ratio_vs_xB.txt"
    
    # Check if file exists
    if not os.path.exists(output_file):
        print(f"Error: File {output_file} not found.")
        print("Make sure you have run the SRC_analysis_3N program first.")
        return
    
    # Read the data
    xB_centers = []
    ratios = []
    count2N_list = []
    count3N_list = []
    
    with open(output_file, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip empty lines and header lines (starting with #)
            if not line or line.startswith('#'):
                continue
            
            try:
                parts = line.split()
                if len(parts) >= 4:
                    xB_centers.append(float(parts[0]))
                    count2N_list.append(float(parts[1]))
                    count3N_list.append(float(parts[2]))
                    ratios.append(float(parts[3]))
            except (ValueError, IndexError):
                continue
    
    if not ratios:
        print("Error: No data found in the output file.")
        return
    
    xB_centers = np.array(xB_centers)
    ratios = np.array(ratios)
    count2N_list = np.array(count2N_list)
    count3N_list = np.array(count3N_list)
    
    # Create figure with subplots
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # Plot 1: 3N/2N Ratio
    if use_log_scale:
        axes[0].semilogy(xB_centers, ratios, 'bo-', linewidth=2, markersize=8)
        axes[0].set_ylim(bottom=0.001)
    else:
        axes[0].plot(xB_centers, ratios, 'bo-', linewidth=2, markersize=8)
        axes[0].set_ylim(bottom=0)
    axes[0].set_xlabel('$x_B$', fontsize=12)
    axes[0].set_ylabel('3N/2N Ratio', fontsize=12)
    axes[0].set_title('3N to 2N Ratio vs $x_B$', fontsize=13, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    
    # Plot 2: 2N Counts
    if use_log_scale:
        axes[1].semilogy(xB_centers, count2N_list, 'go-', linewidth=2, markersize=8, label='2N')
        axes[1].grid(True, alpha=0.3, which='both')
    else:
        axes[1].plot(xB_centers, count2N_list, 'go-', linewidth=2, markersize=8, label='2N')
        axes[1].grid(True, alpha=0.3)
    axes[1].set_xlabel('$x_B$', fontsize=12)
    axes[1].set_ylabel('Count', fontsize=12)
    axes[1].set_title('2N Event Counts vs $x_B$', fontsize=13, fontweight='bold')
    axes[1].legend()
    
    # Plot 3: 3N Counts
    if use_log_scale:
        axes[2].semilogy(xB_centers, count3N_list, 'rs-', linewidth=2, markersize=8, label='3N')
        axes[2].grid(True, alpha=0.3, which='both')
    else:
        axes[2].plot(xB_centers, count3N_list, 'rs-', linewidth=2, markersize=8, label='3N')
        axes[2].grid(True, alpha=0.3)
    axes[2].set_xlabel('$x_B$', fontsize=12)
    axes[2].set_ylabel('Count', fontsize=12)
    axes[2].set_title('3N Event Counts vs $x_B$', fontsize=13, fontweight='bold')
    axes[2].legend()
    
    plt.tight_layout()
    
    # Save the figure
    output_dir = "analysis_output/png_files/ratio_plots"
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "3N_2N_ratio_vs_xB.png")
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Plot saved to: {output_path}")
    
    # Display the plot
    plt.show()
    
    # Print summary
    print("\n" + "="*60)
    print("3N/2N Ratio Summary")
    print("="*60)
    print(f"{'xB Center':<12} {'2N Count':<12} {'3N Count':<12} {'3N/2N Ratio':<12}")
    print("-"*60)
    for xB, c2N, c3N, ratio in zip(xB_centers, count2N_list, count3N_list, ratios):
        print(f"{xB:<12.4f} {c2N:<12.0f} {c3N:<12.0f} {ratio:<12.4f}")
    print("="*60)

if __name__ == "__main__":
    plot_3N_2N_ratio()
