#!/usr/bin/env python3
"""
Simple plotting script for 1D histograms generated by SRC_analysis_2N
Automatically detects and plots any available 1D histogram files.
Analogous to plot_1D_histograms.py for 3N analysis.
"""

import matplotlib.pyplot as plt
import numpy as np
import os
import glob
import warnings

# Try to import scipy for Gaussian fitting, fallback gracefully if not available
try:
    from scipy.optimize import curve_fit
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False
    print("Warning: scipy not available. Gaussian fitting will be disabled.")

def load_fsi_stats(filepath="analysis_output_2N/txt_files/fsi_event_stats.txt"):
    """Load key-value FSI stats written by SRC_analysis_2N.cpp."""
    if not os.path.exists(filepath):
        return None

    stats = {}
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            key, val = parts[0], parts[1]
            try:
                if any(ch in val for ch in ['.', 'e', 'E']):
                    stats[key] = float(val)
                else:
                    stats[key] = int(val)
            except ValueError:
                continue
    return stats

def print_fsi_stats_summary(stats):
    """Print a compact FSI summary including CX and pion production stats."""
    if not stats:
        print("\nFSI stats file not found (analysis_output_2N/txt_files/fsi_event_stats.txt).")
        print("Run SRC_analysis_2N first to generate CX/pion statistics.")
        return

    accepted = int(stats.get('accepted_events', 0))
    cx_any = int(stats.get('events_with_any_cx', 0))
    cx_lead = int(stats.get('events_with_lead_cx', 0))
    cx_recoil = int(stats.get('events_with_recoil_cx', 0))
    cx_total = int(stats.get('total_cx_transitions', 0))
    pion_any = int(stats.get('events_with_any_pion', 0))
    pi_total = int(stats.get('total_pions', 0))
    pi_plus = int(stats.get('total_pi_plus', 0))
    pi_minus = int(stats.get('total_pi_minus', 0))
    pi_zero = int(stats.get('total_pi_zero', 0))
    secondaries = int(stats.get('total_secondaries', 0))

    frac_cx = stats.get('frac_events_with_any_cx', (cx_any / max(accepted, 1)))
    frac_pion = stats.get('frac_events_with_any_pion', (pion_any / max(accepted, 1)))
    avg_pions = stats.get('avg_pions_per_event', (pi_total / max(accepted, 1)))
    avg_secondaries = stats.get('avg_secondaries_per_event', (secondaries / max(accepted, 1)))

    print("\nFSI channel statistics (from fsi_event_stats.txt)")
    print("------------------------------------------------")
    print(f"Accepted events:         {accepted}")
    print(f"Events with any CX:      {cx_any} ({100.0 * frac_cx:.2f}%)")
    print(f"  Lead CX events:        {cx_lead}")
    print(f"  Recoil CX events:      {cx_recoil}")
    print(f"Total CX transitions:    {cx_total}")
    print(f"Events with any pion:    {pion_any} ({100.0 * frac_pion:.2f}%)")
    print(f"Total pions produced:    {pi_total} [pi+={pi_plus}, pi-={pi_minus}, pi0={pi_zero}]")
    print(f"Total secondaries:       {secondaries}")
    print(f"Avg secondaries/event:   {avg_secondaries:.4f}")
    print(f"Avg pions/event:         {avg_pions:.4f}")

def ensure_output_directories():
    """Create output directories for organizing PNG files"""
    base_dir = "analysis_output_2N/png_files"
    subdirs = [
        "individual_plots",
        "grouped_plots", 
        "overview_plots",
        "ratio_plots"
    ]
    
    for subdir in subdirs:
        full_path = os.path.join(base_dir, subdir)
        os.makedirs(full_path, exist_ok=True)
    
    return base_dir

def discover_histogram_files():
    """Discover all available 1D histogram files and extract variable names"""
    # Look in the analysis_output_2N/txt_files directory
    pattern = "analysis_output_2N/txt_files/hist_*_1D.txt"
    files = glob.glob(pattern)
    
    # Extract variable names from filenames
    variables = []
    for filepath in files:
        # Get just the filename without the directory path
        filename = os.path.basename(filepath)
        # Remove 'hist_' prefix and '_1D.txt' suffix
        var_name = filename.replace('hist_', '').replace('_1D.txt', '')
        variables.append(var_name)
    
    return sorted(variables)  # Sort for consistent ordering

def load_histogram(var_name, use_average_weight=False, weight_filter_percentile=98.0):
    """Load histogram data for a given variable name
    
    Args:
        var_name: Variable name (e.g., 'xB', 'Q2')
        use_average_weight: If True, return weight/count, if False return total weight
        weight_filter_percentile: Filter out weights above this percentile (default 98%)
    """
    filename = f"analysis_output_2N/txt_files/hist_{var_name}_1D.txt"
    if not os.path.exists(filename):
        print(f"Warning: File {filename} not found")
        return None, None
    
    data = np.loadtxt(filename, comments='#')
    if data.size == 0:
        print(f"Warning: No data in {filename}")
        return None, None
    
    x = data[:, 0]  # bin centers
    if data.shape[1] >= 3:
        # File has format: bin_center, total_weight, count
        total_weight = data[:, 1]
        count = data[:, 2]
        
        if use_average_weight:
            # Calculate average weight per event, avoid division by zero
            y = np.divide(total_weight, count, out=np.zeros_like(total_weight), where=count!=0)
        else:
            y = total_weight
    else:
        # File has format: bin_center, weight (assume count=1)
        y = data[:, 1]
        if use_average_weight:
            print(f"Warning: {filename} doesn't have count data, showing total weight")
    
    # Filter out weights that are too big
    if weight_filter_percentile < 100:
        # Only filter if there are non-zero weights
        non_zero_weights = y[y > 0]
        if len(non_zero_weights) > 0:
            weight_threshold = np.percentile(non_zero_weights, weight_filter_percentile)
            original_max = np.max(y)
            
            # Remove bins with weights above the threshold
            mask = y <= weight_threshold
            n_filtered = int(np.sum(~mask))
            if n_filtered > 0:
                print(f"  {var_name}: Removed {n_filtered} bins with weights > {weight_threshold:.3e} (was {original_max:.3e})")

            # Apply mask to both x and y
            x = x[mask]
            y = y[mask]

            # If all bins were removed, return None so caller can skip plotting
            if y.size == 0:
                print(f"  {var_name}: All bins removed by filtering; no data to plot.")
                return None, None
    
    return x, y

def get_variable_info(var_name):
    """Get display information for variables - provides sensible defaults for unknown variables"""
    # Common color palette for consistent plotting
    colors = ['blue', 'red', 'green', 'orange', 'purple', 'brown', 'pink', 'gray', 
              'olive', 'cyan', 'magenta', 'lime', 'navy', 'maroon', 'teal', 'gold']
    
    # Predefined info for known variables
    known_vars = {
        'xB': {'label': r'$x_B$', 'color': 'blue'},
        'Q2': {'label': r'$Q^2$ (GeV$^2$)', 'color': 'green'},
        'theta12': {'label': r'$\theta_{12}$ (degrees)', 'color': 'purple'},
        'Lead Nucleon Momentum': {'label': r'Lead Nucleon Momentum (GeV/c)', 'color': 'red'},
        'Recoil Nucleon Momentum': {'label': r'Recoil Nucleon Momentum (GeV/c)', 'color': 'orange'},
        'pmiss': {'label': r'$p_{miss}$ (GeV/c)', 'color': 'brown'},
    }
    
    if var_name in known_vars:
        return known_vars[var_name]
    else:
        # Generate a color based on variable name hash for consistency
        color_idx = hash(var_name) % len(colors)
        # Create a sensible label by replacing underscores and adding units if detected
        label = var_name.replace('_', ' ')
        if 'theta' in var_name.lower() or 'phi' in var_name.lower() or 'angle' in var_name.lower():
            label += ' (degrees)'
        elif 'mom' in var_name.lower() or var_name.startswith('p') and 'after' in var_name:
            label += ' (GeV/c)'
        elif var_name == 'Q2':
            label = r'$Q^2$ (GeV$^2$)'
        return {'label': label, 'color': colors[color_idx]}

def plot_single_histogram(var_name, use_average_weight=False, weight_filter_percentile=98.0, xlim=None):
    """Plot a single histogram with optional x-axis limits"""
    x, y = load_histogram(var_name, use_average_weight, weight_filter_percentile)
    if x is None:
        return
    info = get_variable_info(var_name)
    plt.figure(figsize=(8, 6))
    plt.plot(x, y, '-', color=info['color'], linewidth=2)
    plt.xlabel(info['label'], fontsize=14)
    # Set appropriate y-label based on mode
    if use_average_weight:
        plt.ylabel('Average Weight per Event', fontsize=14)
        plot_type = 'Average Weight'
    else:
        plt.ylabel('Total Weight', fontsize=14)
        plot_type = 'Total Weight'
    # Set x-axis limits to only show significant data with small padding
    if xlim is not None:
        max_y = np.max(y)
        threshold = 0.01 * max_y
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
            plt.xlim(x_min - padding, x_max + padding)
        else:
            plt.xlim(xlim)
    else:
        max_y = np.max(y)
        threshold = 0.01 * max_y
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
            plt.xlim(x_min - padding, x_max + padding)
    filter_note = " (filtered)" if weight_filter_percentile < 100 else ""
    plt.title(f'1D Histogram: {info["label"]} ({plot_type}){filter_note}', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    # Save the plot with appropriate filename
    suffix = '_avg' if use_average_weight else '_total'
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    # Replace spaces and special characters for safe filename
    safe_var_name = var_name.replace(' ', '_').replace('.', '')
    output_dir = "analysis_output_2N/png_files/individual_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_{safe_var_name}_1D{suffix}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    plt.close()

def discover_variable_groups():
    """Define variable groups for 2N analysis (analogous to 3N groups but without theta23 variables)"""
    groups = {
        # Global kinematics
        'Q2_xB': ['Q2', 'xB'],
        # Outgoing electron
        'Outgoing_e': [
            'Outgoing e angle with beam dir (z)',
            'Outgoing e angle with q dir',
            'Outgoing e mom.'
        ],
        # Incoming lead (before interaction)
        'Incoming_lead': [
            'Incoming lead angle with beam dir (z)',
            'Incoming lead angle with q dir',
            'pmiss'
        ],
        # Recoil nucleon
        'Recoil': [
            'Recoil angle with beam dir (z)',
            'Recoil angle with q dir',
            'Recoil mom.'
        ],
        # Outgoing leading nucleon
        'Outgoing_lead': [
            'Outgoing lead angle with beam dir (z)',
            'Outgoing lead angle with q dir',
            'Outgoing lead mom.'
        ],
        # 2N-specific: nucleon momenta and angles
        'Nucleon_momenta': [
            'Lead Nucleon Momentum',
            'Recoil Nucleon Momentum',
            'theta12'
        ]
    }
    return groups

def plot_grouped_histograms(use_average_weight=False, weight_filter_percentile=98.0):
    """Plot grouped histograms for the groups defined in `discover_variable_groups()`.
    For 2N, we plot regions based on xB ranges instead of theta12-theta23.
    Each group produces one file with one subplot per variable in the group.
    """
    variable_groups = discover_variable_groups()
    if not variable_groups:
        print("No variable groups found")
        return

    # xB-based regions for 2N (analogous to theta-based regions for 3N)
    # Region 0: xB < 1 (QE region)
    # Region 1: 1 < xB < 1.5 (SRC onset)
    # Region 2: 1.5 < xB < 2 (2N SRC)
    # Region 3: 2 < xB < 2.5 (high xB)
    # Region 4: xB > 2.5 (very high xB)
    plot_regions = [0, 1, 2, 3, 4]  # Select key regions: QE, 2N SRC, very high xB
    region_labels = {
        0: 'xB < 1',
        1: '1 < xB < 1.5',
        2: '1.5 < xB < 2',
        3: '2 < xB < 2.5',
        4: 'xB > 2.5'
    }

    colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple']

    for group_name, var_list in variable_groups.items():
        n_vars = len(var_list)
        # Create a vertical stack of subplots (one per variable in the group)
        fig, axes = plt.subplots(n_vars, 1, figsize=(8, 3 * n_vars), squeeze=False)
        axes = axes.flatten()

        for ivar, base_var in enumerate(var_list):
            ax = axes[ivar]
            any_plotted = False
            for i_reg, reg in enumerate(plot_regions):
                hist_name = f"{base_var}_region{reg}"
                x, y = load_histogram(hist_name, use_average_weight, weight_filter_percentile)
                if x is None or y is None:
                    # skip missing files silently
                    continue
                ax.plot(x, y, '-', color=colors[i_reg % len(colors)], linewidth=1.8, label=region_labels.get(reg, f'Region {reg}'))
                any_plotted = True

            info = get_variable_info(base_var)
            ax.set_xlabel(info['label'])
            ax.set_ylabel('Total Weight' if not use_average_weight else 'Avg Weight')
            ax.grid(True, alpha=0.3)
            if any_plotted:
                ax.legend(fontsize=9)
            else:
                ax.text(0.5, 0.5, f'No data for {base_var}', ha='center', va='center', transform=ax.transAxes)

        plt.suptitle(f'{group_name} grouped histograms (2N, xB regions)', fontsize=14)
        plt.tight_layout(rect=[0, 0, 1, 0.96])

        # Save
        safe_name = group_name.replace(' ', '_')
        out_dir = 'analysis_output_2N/png_files/grouped_plots'
        os.makedirs(out_dir, exist_ok=True)
        suffix = '_avg' if use_average_weight else '_total'
        filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
        out_path = os.path.join(out_dir, f'plot_grouped_{safe_name}_2N{suffix}{filter_suffix}.png')
        plt.savefig(out_path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f'Saved grouped plot: {out_path}')

def plot_all_together(use_average_weight=False, weight_filter_percentile=98.0):
    """Plot all histograms as subplots on one page"""
    # Discover available variables
    available_vars = discover_histogram_files()
    if not available_vars:
        print("No histogram files found!")
        return

    # Filter out region-specific variables for the overview
    filtered_vars = [v for v in available_vars if '_region' not in v]

    n_vars = len(filtered_vars)
    cols = 4
    rows = (n_vars + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(16, 4*rows))
    if rows == 1:
        axes = [axes] if cols == 1 else axes
    else:
        axes = axes.flatten()

    plot_idx = 0
    for var_name in filtered_vars:
        x, y = load_histogram(var_name, use_average_weight, weight_filter_percentile)
        if x is None:
            continue
        info = get_variable_info(var_name)
        axes[plot_idx].plot(x, y, '-', color=info['color'], linewidth=2)
        axes[plot_idx].set_xlabel(info['label'], fontsize=12)
        if use_average_weight:
            axes[plot_idx].set_ylabel('Avg Weight', fontsize=12)
            plot_type = 'Average Weight'
        else:
            axes[plot_idx].set_ylabel('Total Weight', fontsize=12)
            plot_type = 'Total Weight'
        max_y = np.max(y)
        threshold = 0.01 * max_y
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
            axes[plot_idx].set_xlim(x_min - padding, x_max + padding)
        axes[plot_idx].set_title(f'{info["label"]}', fontsize=14)
        axes[plot_idx].grid(True, alpha=0.3)
        plot_idx += 1

    for i in range(plot_idx, len(axes)):
        axes[i].set_visible(False)
    main_title = f'All 1D Histograms - 2N Analysis ({plot_type})'
    plt.suptitle(main_title, fontsize=18)
    plt.tight_layout()
    suffix = '_avg' if use_average_weight else '_total'
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    output_dir = "analysis_output_2N/png_files/overview_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_all_histograms_2N{suffix}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    plt.close()

def plot_ratio(var1_name, var2_name, weight_filter_percentile=98.0):
    """Plot the ratio of total weights between two variables (var1 / var2)"""
    # Load both histograms
    x1, y1 = load_histogram(var1_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
    x2, y2 = load_histogram(var2_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
    
    if x1 is None or x2 is None:
        print(f"Error: Could not load histograms for {var1_name} and/or {var2_name}")
        return
    
    # Check if the histograms have the same binning
    if len(x1) != len(x2) or not np.allclose(x1, x2, rtol=1e-10):
        print(f"Warning: {var1_name} and {var2_name} have different binning.")
        # Use simple interpolation
        if len(x1) <= len(x2):
            x_common = x1
            y1_common = y1
            y2_common = np.interp(x1, x2, y2)
        else:
            x_common = x2
            y2_common = y2
            y1_common = np.interp(x2, x1, y1)
    else:
        x_common = x1
        y1_common = y1
        y2_common = y2
    
    # Calculate ratio, avoiding division by zero
    ratio = np.divide(y1_common, y2_common, out=np.zeros_like(y1_common), where=y2_common!=0)
    
    # Get variable info for labels
    info1 = get_variable_info(var1_name)
    info2 = get_variable_info(var2_name)
    
    plt.figure(figsize=(8, 6))
    plt.plot(x_common, ratio, '-', color='black', linewidth=2)
    plt.xlabel(f'{info1["label"]} (same binning as {info2["label"]})', fontsize=14)
    plt.ylabel(f'Ratio: {var1_name} / {var2_name}', fontsize=14)
    
    # Set x-axis limits
    max_combined = np.max([np.max(y1_common), np.max(y2_common)])
    threshold = 0.01 * max_combined
    significant_mask = (y1_common > threshold) | (y2_common > threshold)
    if np.any(significant_mask):
        x_min, x_max = x_common[significant_mask].min(), x_common[significant_mask].max()
        x_range = x_max - x_min
        padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
        plt.xlim(x_min - padding, x_max + padding)
    
    filter_note = " (filtered)" if weight_filter_percentile < 100 else ""
    plt.title(f'Ratio: {var1_name} / {var2_name}{filter_note}', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    # Save the plot
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    safe_var1 = var1_name.replace(' ', '_').replace('.', '')
    safe_var2 = var2_name.replace(' ', '_').replace('.', '')
    output_dir = "analysis_output_2N/png_files/ratio_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_ratio_{safe_var1}_over_{safe_var2}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # Print statistics
    valid_ratio_mask = (y2_common != 0) & np.isfinite(ratio)
    if np.any(valid_ratio_mask):
        valid_ratios = ratio[valid_ratio_mask]
        print(f"\nRatio statistics for {var1_name} / {var2_name}:")
        print(f"  Mean ratio: {np.mean(valid_ratios):.4f}")
        print(f"  Median ratio: {np.median(valid_ratios):.4f}")
        print(f"  Min ratio: {np.min(valid_ratios):.4f}")
        print(f"  Max ratio: {np.max(valid_ratios):.4f}")

def plot_multiple_ratios(ratio_pairs, weight_filter_percentile=98.0, title=None):
    """Plot multiple ratio graphs together on the same figure"""
    if not ratio_pairs:
        print("No ratio pairs provided")
        return
    
    import matplotlib.cm as cm
    n_curves = len(ratio_pairs)
    cmap = cm.get_cmap('plasma')
    colors = [cmap(i / max(n_curves - 1, 1)) for i in range(n_curves)]

    plt.figure(figsize=(10, 6))

    all_x_mins, all_x_maxs = [], []

    for i, (var1_name, var2_name) in enumerate(ratio_pairs):
        x1, y1 = load_histogram(var1_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
        x2, y2 = load_histogram(var2_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)

        if x1 is None or x2 is None:
            print(f"Error: Could not load histograms for {var1_name} and/or {var2_name}")
            continue

        if len(x1) != len(x2) or not np.allclose(x1, x2, rtol=1e-10):
            if len(x1) <= len(x2):
                x_common = x1
                y1_common = y1
                y2_common = np.interp(x1, x2, y2)
            else:
                x_common = x2
                y2_common = y2
                y1_common = np.interp(x2, x1, y1)
        else:
            x_common = x1
            y1_common = y1
            y2_common = y2

        ratio = np.divide(y1_common, y2_common, out=np.zeros_like(y1_common), where=y2_common!=0)

        color = colors[i]
        label = f'{var1_name} / {var2_name}'
        plt.plot(x_common, ratio, '-', color=color, linewidth=2, label=label)

        max_combined = np.max([np.max(y1_common), np.max(y2_common)])
        threshold = 0.01 * max_combined
        significant_mask = (y1_common > threshold) | (y2_common > threshold)
        if np.any(significant_mask):
            x_min, x_max = x_common[significant_mask].min(), x_common[significant_mask].max()
            all_x_mins.append(x_min)
            all_x_maxs.append(x_max)
    
    if all_x_mins and all_x_maxs:
        x_min_global = min(all_x_mins)
        x_max_global = max(all_x_maxs)
        x_range = x_max_global - x_min_global
        padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max_global)
        plt.xlim(x_min_global - padding, x_max_global + padding)
    
    if ratio_pairs:
        info1 = get_variable_info(ratio_pairs[0][0])
        plt.xlabel(info1['label'], fontsize=14)
    
    plt.ylabel('Ratio', fontsize=14)
    
    if title:
        plot_title = title
    else:
        if len(ratio_pairs) == 1:
            plot_title = f'Ratio: {ratio_pairs[0][0]} / {ratio_pairs[0][1]}'
        else:
            plot_title = 'Multiple Ratio Comparison (2N)'
    
    filter_note = " (filtered)" if weight_filter_percentile < 100 else ""
    plt.title(f'{plot_title}{filter_note}', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    ratio_names = '_'.join([f"{r[0].replace(' ', '_').replace('.', '')}_over_{r[1].replace(' ', '_').replace('.', '')}" for r in ratio_pairs])
    output_dir = "analysis_output_2N/png_files/ratio_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_multiple_ratios_{ratio_names}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    plt.close()

def main():
    """Main function to generate all plots"""
    # Set global font sizes for matplotlib
    import matplotlib
    matplotlib.rcParams.update({
        'font.size': 12,
        'axes.titlesize': 16,
        'axes.labelsize': 14,
        'xtick.labelsize': 12,
        'ytick.labelsize': 12,
        'legend.fontsize': 12,
    })
    
    # Ensure output directories exist
    base_output_dir = ensure_output_directories()
    
    # Configuration
    use_average_weight = False  # When true, displays total_bin_weight / bin_event_count
    weight_filter_percentile = 100.0  # Set to 100 to disable filtering
    
    # Discover available variables
    available_vars = discover_histogram_files()
    print("2N SRC Analysis Plotting Script")
    print("================================")
    print("Available variables:", available_vars)

    # Print FSI statistics (CX, pion production, secondaries)
    print_fsi_stats_summary(load_fsi_stats())

    if not available_vars:
        print("No histogram files found! Please run SRC_analysis_2N first.")
        return

    # Generate individual plots for each variable
    print("\nGenerating individual plots...")
    for var in available_vars:
        if '_region' not in var:  # Skip region-specific histograms for individual plots
            plot_single_histogram(var, use_average_weight=use_average_weight, weight_filter_percentile=weight_filter_percentile)
            print(f"  Saved individual plot for: {var}")

    # Generate grouped plots (by xB region)
    print("\nGenerating grouped plots by xB regions...")
    plot_grouped_histograms(use_average_weight=use_average_weight, weight_filter_percentile=weight_filter_percentile)

    # Generate overview plot
    print("\nGenerating overview plot...")
    plot_all_together(use_average_weight=use_average_weight, weight_filter_percentile=weight_filter_percentile)

    print(f"\nAll plots saved to: {base_output_dir}")
    print("Plotting complete!")

if __name__ == "__main__":
    main()