#!/usr/bin/env python3
"""
Simple plotting script for 1D histograms generated by analysis
Automatically detects and plots any available 1D histogram files.

Usage:
    python plot_1D_histograms.py              # Default: theta-based regions (3N style)
    python plot_1D_histograms.py --xB         # Use xB-based regions (for comparison with 2N)
    python plot_1D_histograms.py --mode xB    # Same as above
    python plot_1D_histograms.py --mode theta # Explicitly use theta-based regions
"""

import matplotlib.pyplot as plt
import numpy as np
import os
import glob
import warnings
import argparse

# Try to import scipy for Gaussian fitting, fallback gracefully if not available
try:
    from scipy.optimize import curve_fit
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False
    print("Warning: scipy not available. Gaussian fitting will be disabled.")

def ensure_output_directories():
    """Create output directories for organizing PNG files"""
    base_dir = "analysis_output/png_files"
    subdirs = [
        "individual_plots",
        "grouped_plots", 
        "overview_plots",
        "ratio_plots"
    ]
    
    for subdir in subdirs:
        full_path = os.path.join(base_dir, subdir)
        os.makedirs(full_path, exist_ok=True)
    
    return base_dir

def discover_histogram_files():
    """Discover all available 1D histogram files and extract variable names"""
    # Look in the analysis_output/txt_files directory
    pattern = "analysis_output/txt_files/hist_*_1D.txt"
    files = glob.glob(pattern)
    
    # Extract variable names from filenames
    variables = []
    for filepath in files:
        # Get just the filename without the directory path
        filename = os.path.basename(filepath)
        # Remove 'hist_' prefix and '_1D.txt' suffix
        var_name = filename.replace('hist_', '').replace('_1D.txt', '')
        variables.append(var_name)
    
    return sorted(variables)  # Sort for consistent ordering

def load_histogram(var_name, use_average_weight=False, weight_filter_percentile=98.0):
    """Load histogram data for a given variable name
    
    Args:
        var_name: Variable name (e.g., 'xB', 'Q2')
        use_average_weight: If True, return weight/count, if False return total weight
        weight_filter_percentile: Filter out weights above this percentile (default 99.5%)
    """
    filename = f"analysis_output/txt_files/hist_{var_name}_1D.txt"
    if not os.path.exists(filename):
        print(f"Warning: File {filename} not found")
        return None, None
    
    data = np.loadtxt(filename, comments='#')
    if data.size == 0:
        print(f"Warning: No data in {filename}")
        return None, None
    
    x = data[:, 0]  # bin centers
    if data.shape[1] >= 3:
        # File has format: bin_center, total_weight, count
        total_weight = data[:, 1]
        count = data[:, 2]
        
        if use_average_weight:
            # Calculate average weight per event, avoid division by zero
            y = np.divide(total_weight, count, out=np.zeros_like(total_weight), where=count!=0)
        else:
            y = total_weight
    else:
        # File has format: bin_center, weight (assume count=1)
        y = data[:, 1]
        if use_average_weight:
            print(f"Warning: {filename} doesn't have count data, showing total weight")
    
    # Filter out weights that are too big
    if weight_filter_percentile < 100:
        # Only filter if there are non-zero weights
        non_zero_weights = y[y > 0]
        if len(non_zero_weights) > 0:
            weight_threshold = np.percentile(non_zero_weights, weight_filter_percentile)
            original_max = np.max(y)
            
            # Remove bins with weights above the threshold (don't just clip)
            mask = y <= weight_threshold
            n_filtered = int(np.sum(~mask))
            if n_filtered > 0:
                print(f"  {var_name}: Removed {n_filtered} bins with weights > {weight_threshold:.3e} (was {original_max:.3e})")

            # Apply mask to both x and y
            x = x[mask]
            y = y[mask]

            # If all bins were removed, return None so caller can skip plotting
            if y.size == 0:
                print(f"  {var_name}: All bins removed by filtering; no data to plot.")
                return None, None
    
    return x, y

def get_variable_info(var_name):
    """Get display information for variables - provides sensible defaults for unknown variables"""
    # Common color palette for consistent plotting
    colors = ['blue', 'red', 'green', 'orange', 'purple', 'brown', 'pink', 'gray', 
              'olive', 'cyan', 'magenta', 'lime', 'navy', 'maroon', 'teal', 'gold']
    
    # Predefined info for known variables
    known_vars = {
        'xB': {'label': r'$x_B$', 'color': 'blue'},
        'Q2': {'label': r'$Q^2$ (GeV$^2$)', 'color': 'green'},
        # 'pq': {'label': r'$p_q$ (GeV/c)', 'color': 'red'},
        # 'Theta pq': {'label': r'$\theta_{pq}$ (degrees)', 'color': 'orange'},
        # 'Scattering Angle': {'label': r'Scattering Angle (degrees)', 'color': 'purple'},
        # 'Incoming lead angle': {'label': r'Incoming Lead Angle (degrees)', 'color': 'brown'},
        # 'Incoming lead mom.': {'label': r'Incoming Lead Mom. (GeV/c)', 'color': 'pink'},
        # 'Outgoing lead angle': {'label': r'Outgoing Lead Angle (degrees)', 'color': 'gray'},
        # 'Outgoing lead mom.': {'label': r'Outgoing Lead Mom. (GeV/c)', 'color': 'olive'},
        # 'Outgoing e mom.': {'label': r'Outgoing $e$ Mom. (GeV/c)', 'color': 'cyan'},
        
        # 'pmiss': {'label': r'$p_{miss}$ (GeV/c)', 'color': 'red'},
        # 'p1_theta': {'label': r'$p_1 \theta$ (degrees)', 'color': 'orange'},
        # 'p1_phi': {'label': r'$p_1 \phi$ (degrees)', 'color': 'purple'},
        # 'p2_theta': {'label': r'$p_2 \theta$ (degrees)', 'color': 'brown'},
        # 'p2_phi': {'label': r'$p_2 \phi$ (degrees)', 'color': 'pink'},
        # 'p3_theta': {'label': r'$p_3 \theta$ (degrees)', 'color': 'gray'},
        # 'p3_phi': {'label': r'$p_3 \phi$ (degrees)', 'color': 'olive'},
        # 'p1_after_mag': {'label': r'$|p_1|$ after (GeV/c)', 'color': 'cyan'},
        # 'p1_after_theta': {'label': r'$p_1$ after $\theta$ (degrees)', 'color': 'magenta'},
        # 'p1_unsorted_theta': {'label': r'$p_1$ unsorted $\theta$ (degrees)', 'color': 'lime'},
        # 'p2_unsorted_theta': {'label': r'$p_2$ unsorted $\theta$ (degrees)', 'color': 'navy'},
        # 'p3_unsorted_theta': {'label': r'$p_3$ unsorted $\theta$ (degrees)', 'color': 'maroon'},
        # 'e_after_theta': {'label': r'$e$ after $\theta$ (degrees)', 'color': 'darkred'},
        # 'e_after_phi': {'label': r'$e$ after $\phi$ (degrees)', 'color': 'darkblue'},
        # 'e_after_mag': {'label': r'$|e|$ after (GeV/c)', 'color': 'darkgreen'}

        'Lead Nucleon Momentum': {'label': r'Lead Nucleon Momentum (GeV/c)', 'color': 'red'},
        'Recoil1 Nucleon Momentum': {'label': r'Recoil1 Nucleon Momentum (GeV/c)', 'color': 'orange'},
        'Recoil2 Nucleon Momentum': {'label': r'Recoil2 Nucleon Momentum (GeV/c)', 'color': 'purple'}
        ,
        'alpha_q': {'label': r'$\alpha_q = (\nu - |\vec{q}|)/m_N$', 'color': 'navy'},
        'alpha_p_final': {'label': r'$\alpha_{p}^{final}$', 'color': 'teal'},
        'alpha_deutron': {'label': r'$\alpha_{d}$', 'color': 'brown'},
        'alpha_p_initial': {'label': r'$\alpha_{p}^{initial}$', 'color': 'magenta'},
        'alpha_sum': {'label': r'$\alpha_{p}^{initial} + \alpha_{d}$', 'color': 'black'}
    }
    
    if var_name in known_vars:
        return known_vars[var_name]
    else:
        # Generate a color based on variable name hash for consistency
        color_idx = hash(var_name) % len(colors)
        # Create a sensible label by replacing underscores and adding units if detected
        label = var_name.replace('_', ' ')
        if 'theta' in var_name or 'phi' in var_name:
            label += ' (degrees)'
        elif 'mag' in var_name or var_name.startswith('p') and 'after' in var_name:
            label += ' (GeV/c)'
        elif var_name == 'Q2':
            label = r'$Q^2$ (GeV$^2$)'
        return {'label': label, 'color': colors[color_idx]}

def gaussian(x, amplitude, mean, sigma, offset=0):
    """Gaussian function for curve fitting"""
    return amplitude * np.exp(-0.5 * ((x - mean) / sigma) ** 2) + offset

def fit_gaussian_to_peak(x, y, peak_fraction=0.1, min_r_squared=0.3):
    """Fit a Gaussian to the peak region of histogram data
    
    Args:
        x: x values (bin centers)
        y: y values (weights)
        peak_fraction: fraction of peak height to use for fitting region (0.1 = 10% of peak height)
        min_r_squared: minimum R-squared value to consider fit "good"
        
    Returns:
        dict with 'success', 'peak_center', 'r_squared', 'fit_params' or None if fit failed
    """
    if not SCIPY_AVAILABLE:
        print("    Scipy not available")
        return {
            'success': False,
            'peak_center': None,
            'r_squared': 0.0,
            'fit_params': None,
            'error': 'scipy not available'
        }
        
    if len(x) < 3 or len(y) < 3: 
        print(f"    Not enough points: x={len(x)}, y={len(y)}")
        return {
            'success': False,
            'peak_center': None,
            'r_squared': 0.0,
            'fit_params': None,
            'error': 'not enough points'
        }
    
    # Find peak
    peak_idx = np.argmax(y)
    peak_x = x[peak_idx]
    peak_y = y[peak_idx]
    
    if peak_y <= 0:
        print(f"    Peak value is non-positive: {peak_y}")
        return {
            'success': False,
            'peak_center': None,
            'r_squared': 0.0,
            'fit_params': None,
            'error': 'non-positive peak'
        }
    
    # Use a much broader fitting region - include points above peak_fraction of peak height
    # This will include many more points around the peak
    threshold = peak_fraction * peak_y
    fit_mask = y >= threshold
    
    # If too few points above threshold, use a fixed number of points around peak
    if np.sum(fit_mask) < 5:
        # Use points around the peak index - take up to 10 points on each side
        half_window = min(10, len(x) // 4)  # Use up to 1/4 of all points, max 10 on each side
        start_idx = max(0, peak_idx - half_window)
        end_idx = min(len(x), peak_idx + half_window + 1)
        fit_mask = np.zeros_like(y, dtype=bool)
        fit_mask[start_idx:end_idx] = True
    
    # Ensure we have at least 3 points for fitting
    if np.sum(fit_mask) < 3:
        print(f"    Not enough points for fitting: {np.sum(fit_mask)}")
        return {
            'success': False,
            'peak_center': None,
            'r_squared': 0.0,
            'fit_params': None,
            'error': 'insufficient fitting points'
        }
    
    x_fit = x[fit_mask]
    y_fit = y[fit_mask]
    
    print(f"    Fitting with {len(x_fit)} points, peak_y={peak_y:.3e}, x_range={x_fit.max() - x_fit.min():.3f}")
    
    try:
        # Initial guess: amplitude=peak_y, mean=peak_x, sigma=rough estimate, offset=min(y_fit)
        x_range = x_fit.max() - x_fit.min()
        initial_sigma = max(x_range / 6, (x[1] - x[0]) if len(x) > 1 else 1.0)  # More reasonable sigma guess
        initial_offset = np.min(y_fit) * 0.5  # Small offset
        
        # More lenient bounds
        lower_bounds = [
            0, 
            x_fit.min() - x_range,  
            (x[1] - x[0]) / 10 if len(x) > 1 else 0.001,  
            -peak_y  
        ]
        upper_bounds = [
            peak_y * 20,  
            x_fit.max() + x_range, 
            x_range * 2, 
            peak_y 
        ]
        
        # Suppress scipy warnings for cleaner output
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            popt, _ = curve_fit(
                gaussian, x_fit, y_fit,
                p0=[peak_y, peak_x, initial_sigma, initial_offset],
                bounds=(lower_bounds, upper_bounds),
                maxfev=2000  # More iterations
            )
        
        # Calculate R-squared
        y_pred = gaussian(x_fit, *popt)
        ss_res = np.sum((y_fit - y_pred) ** 2)
        ss_tot = np.sum((y_fit - np.mean(y_fit)) ** 2)
        r_squared = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0
        
        # TEMPORARY: Accept all fits regardless of quality to see what we get
        return {
            'success': True,  # Always accept the fit
            'peak_center': popt[1],  # mean parameter
            'r_squared': r_squared,
            'fit_params': popt
        }
    
    except Exception as e:
        # For debugging - let's see what's going wrong
        print(f"    Fitting failed with error: {e}")
        return {
            'success': False,
            'peak_center': None,
            'r_squared': 0.0,
            'fit_params': None,
            'error': str(e)
        }

def plot_single_histogram(var_name, use_average_weight=False, weight_filter_percentile=98.0, xlim=None):
    """Plot a single histogram with optional x-axis limits"""
    x, y = load_histogram(var_name, use_average_weight, weight_filter_percentile)
    if x is None:
        return
    info = get_variable_info(var_name)
    plt.figure(figsize=(8, 6))
    plt.plot(x, y, '-', color=info['color'], linewidth=2)
    plt.xlabel(info['label'], fontsize=14)
    # Set appropriate y-label based on mode
    if use_average_weight:
        plt.ylabel('Average Weight per Event', fontsize=14)
        plot_type = 'Average Weight'
    else:
        plt.ylabel('Total Weight', fontsize=14)
        plot_type = 'Total Weight'
    # Set x-axis limits to only show significant data (above threshold) with small padding
    if xlim is not None:
        # Only use nonzero or significant bins for xlim
        max_y = np.max(y)
        threshold = 0.01 * max_y
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
            plt.xlim(x_min - padding, x_max + padding)
        else:
            plt.xlim(xlim)
    else:
        max_y = np.max(y)
        threshold = 0.01 * max_y  # Consider data below 1% of max as insignificant
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            # Fixed alpha plot limits and ticks (use exact ranges requested)
            alpha_limits = {
                'alpha_q': (-1.6, -0.2),
                'alpha_deutron': (1.0, 2.0),
                'alpha_p_final': (0.0, 1.0),
                'alpha_p_initial': (1.0, 2.0)
            }
            if var_name in alpha_limits:
                left, right = alpha_limits[var_name]
                plt.xlim(left, right)
                try:
                    ticks = np.arange(left, right + 1e-9, 0.1)
                    plt.xticks(ticks)
                    ax = plt.gca()
                    try:
                        if ax.get_yscale() == 'linear':
                            ax.set_aspect('equal', adjustable='box')
                    except Exception:
                        pass
                except Exception:
                    pass
            else:
                padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
                plt.xlim(x_min - padding, x_max + padding)
    filter_note = " (filtered)" if weight_filter_percentile < 100 else ""
    plt.title(f'1D Histogram: {info["label"]} ({plot_type}){filter_note}', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    # Save the plot with appropriate filename
    suffix = '_avg' if use_average_weight else '_total'
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    # Replace spaces and special characters for safe filename
    safe_var_name = var_name.replace(' ', '_').replace('.', '')
    output_dir = "analysis_output/png_files/individual_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_{safe_var_name}_1D{suffix}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    # If this is an alpha plot, show it interactively before closing
    alpha_keys = {'alpha_q', 'alpha_deutron', 'alpha_p_final', 'alpha_p_initial', 'alpha_sum'}
    if var_name in alpha_keys:
        try:
            plt.show()
        except Exception:
            pass
    plt.close()

def plot_ratio(var1_name, var2_name, weight_filter_percentile=98.0):
    """Plot the ratio of total weights between two variables (var1 / var2)
    
    Args:
        var1_name: First variable name (numerator)
        var2_name: Second variable name (denominator)
        weight_filter_percentile: Filter out weights above this percentile
    """
    # Load both histograms (always use total weight for ratios)
    x1, y1 = load_histogram(var1_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
    x2, y2 = load_histogram(var2_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
    
    if x1 is None or x2 is None:
        print(f"Error: Could not load histograms for {var1_name} and/or {var2_name}")
        return
    
    # Check if the histograms have the same binning
    if len(x1) != len(x2) or not np.allclose(x1, x2, rtol=1e-10):
        print(f"Warning: {var1_name} and {var2_name} have different binning.")
        try:
            from scipy.interpolate import interp1d
            print("Attempting interpolation using scipy...")
            # Interpolate y2 to match x1 binning
            f = interp1d(x2, y2, kind='linear', bounds_error=False, fill_value=0)
            y2_interp = f(x1)
            x_common = x1
            y1_common = y1
            y2_common = y2_interp
        except ImportError:
            print("Scipy not available. Using simple resampling (may be less accurate).")
            # Simple fallback: use the variable with fewer bins as the common binning
            if len(x1) <= len(x2):
                x_common = x1
                y1_common = y1
                # Simple nearest-neighbor resampling for y2
                y2_common = np.interp(x1, x2, y2)
            else:
                x_common = x2
                y2_common = y2
                # Simple nearest-neighbor resampling for y1
                y1_common = np.interp(x2, x1, y1)
    else:
        x_common = x1
        y1_common = y1
        y2_common = y2
    
    # Calculate ratio, avoiding division by zero
    ratio = np.divide(y1_common, y2_common, out=np.zeros_like(y1_common), where=y2_common!=0)
    
    # Get variable info for labels
    info1 = get_variable_info(var1_name)
    info2 = get_variable_info(var2_name)
    
    plt.figure(figsize=(8, 6))
    plt.plot(x_common, ratio, '-', color='black', linewidth=2)
    plt.xlabel(f'{info1["label"]} (same binning as {info2["label"]})', fontsize=14)
    plt.ylabel(f'Ratio: {var1_name} / {var2_name}', fontsize=14)
    
    # Set x-axis limits to show significant data
    # Use the maximum of both distributions to define significance
    max_combined = np.max([np.max(y1_common), np.max(y2_common)])
    threshold = 0.01 * max_combined
    significant_mask = (y1_common > threshold) | (y2_common > threshold)
    if np.any(significant_mask):
        x_min, x_max = x_common[significant_mask].min(), x_common[significant_mask].max()
        x_range = x_max - x_min
        padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
        plt.xlim(x_min - padding, x_max + padding)
    
    filter_note = " (filtered)" if weight_filter_percentile < 100 else ""
    plt.title(f'Ratio: {var1_name} / {var2_name}{filter_note}', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    # Save the plot
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    # Replace spaces and special characters for safe filename
    safe_var1 = var1_name.replace(' ', '_').replace('.', '')
    safe_var2 = var2_name.replace(' ', '_').replace('.', '')
    output_dir = "analysis_output/png_files/ratio_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_ratio_{safe_var1}_over_{safe_var2}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # Print some statistics
    valid_ratio_mask = (y2_common != 0) & np.isfinite(ratio)
    if np.any(valid_ratio_mask):
        valid_ratios = ratio[valid_ratio_mask]
        print(f"\nRatio statistics for {var1_name} / {var2_name}:")
        print(f"  Mean ratio: {np.mean(valid_ratios):.4f}")
        print(f"  Median ratio: {np.median(valid_ratios):.4f}")
        print(f"  Min ratio: {np.min(valid_ratios):.4f}")
        print(f"  Max ratio: {np.max(valid_ratios):.4f}")
        print(f"  Std ratio: {np.std(valid_ratios):.4f}")

def discover_variable_groups():
    # Groups taken from SRC_analysis_3N.cpp (only uncommented variables)
    # Grouping reflects logical blocks in the C++ saved_vars list.
    groups = {
        # global kinematics
        'Q2_xB': ['Q2', 'xB'],
        # outgoing electron
        'Outgoing_e': [
            'Outgoing e angle with beam dir (z)',
            'Outgoing e angle with q dir',
            'Outgoing e mom.'
        ],
        # incoming lead (before interaction)
        'Incoming_lead': [
            'Incoming lead angle with beam dir (z)',
            'Incoming lead angle with q dir',
            'pmiss'
        ],
        # recoil nucleon(s)
        'Recoil': [
            'Recoil angle with beam dir (z)',
            'Recoil angle with q dir',
            'Recoil mom.'
        ],
        # outgoing leading nucleon
        'Outgoing_lead': [
            'Outgoing lead angle with beam dir (z)',
            'Outgoing lead angle with q dir',
            'Outgoing lead mom.'
        ],
        # nucleon momenta
        'Nucleon_momenta': [
            'Lead Nucleon Momentum',
            'Recoil1 Nucleon Momentum',
            'Recoil2 Nucleon Momentum'
        ]
        ,
        'Lightcone': [
            'alpha_q',
            'alpha_p_final',
            'alpha_deutron',
            'alpha_p_initial',
            'alpha_sum'
        ]
    }
    # Expand each variable to its per-region filename pattern when used
    return groups

def plot_grouped_histograms(use_average_weight=False, weight_filter_percentile=98.0, region_mode='theta', y_log=True):
    """Plot grouped histograms for the groups defined in `discover_variable_groups()`.
    
    Args:
        use_average_weight: If True, show average weight per event
        weight_filter_percentile: Filter out weights above this percentile
        region_mode: 'theta' for theta12-theta23 regions (3N style), 'xB' for xB-based regions
    """
    variable_groups = discover_variable_groups()
    if not variable_groups:
        print("No variable groups found")
        return

    # Define regions based on mode
    if region_mode == 'xB':
        # xB-based regions (same as 2N for comparison)
        plot_regions = [0, 1, 2, 3, 4]  # Select key regions: QE, 2N SRC, very high xB
        region_labels = {
            0: 'xB < 1',
            1: '1 < xB < 1.5',
            2: '1.5 < xB < 2',
            3: '2 < xB < 2.5',
            4: 'xB > 2.5'
        }
        mode_suffix = '_xB_regions'
        title_suffix = '(3N, xB regions)'
    else:
        # Theta-based regions (original 3N style)
        plot_regions = [0,1,2,3,4,5,6]#[0, 2, 6]
        region_labels = {
            0: 'Head rocket',
            2: 'Tail rocket',
            3: "Tail rocket",
            6: 'Star'
        }
        mode_suffix = '_theta_regions'
        title_suffix = '(3N, theta regions)'

    # Expanded color palette to ensure distinct lines per region
    colors = [
        'tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple',
        'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan'
    ]

    for group_name, var_list in variable_groups.items():
        n_vars = len(var_list)
        # Create a vertical stack of subplots (one per variable in the group)
        fig, axes = plt.subplots(n_vars, 1, figsize=(8, 3 * n_vars), squeeze=False)
        axes = axes.flatten()

        for ivar, base_var in enumerate(var_list):
            ax = axes[ivar]
            any_plotted = False
            min_positive_y = None  # Track smallest positive value for log-scale floor
            # For lightcone variables (alpha_*), plot the TOTAL histogram (no per-region files)
            alpha_vars = {'alpha_q', 'alpha_p_final', 'alpha_deutron', 'alpha_p_initial', 'alpha_sum'}
            if base_var in alpha_vars:
                x, y = load_histogram(base_var, use_average_weight, weight_filter_percentile)
                if x is not None and y is not None:
                    ax.plot(x, y, '-', color=colors[0], linewidth=1.8, label='Total')
                    any_plotted = True
                    if y_log:
                        positive_y = y[y > 0]
                        if positive_y.size:
                            min_positive_y = positive_y.min()
                    # Apply fixed alpha limits/ticks when plotting alpha variables
                    alpha_limits = {
                        'alpha_q': (-1.6, -0.2),
                        'alpha_deutron': (1.0, 2.0),
                        'alpha_p_final': (0.0, 1.0),
                        'alpha_p_initial': (1.0, 2.0)
                    }
                    if base_var in alpha_limits:
                        left, right = alpha_limits[base_var]
                        try:
                            ax.set_xlim(left, right)
                            ticks = np.arange(left, right + 1e-9, 0.1)
                            ax.set_xticks(ticks)
                            # Keep aspect ratio square for alpha plots when using linear y-axis
                            if not y_log:
                                try:
                                    ax.set_aspect('equal', adjustable='box')
                                except Exception:
                                    pass
                        except Exception:
                            pass
            else:
                for i_reg, reg in enumerate(plot_regions):
                    hist_name = f"{base_var}_region{reg}"
                    x, y = load_histogram(hist_name, use_average_weight, weight_filter_percentile)
                    if x is None or y is None:
                        # skip missing files silently
                        continue
                    ax.plot(x, y, '-', color=colors[i_reg % len(colors)], linewidth=1.8, label=region_labels.get(reg, f'Region {reg}'))
                    any_plotted = True
                    if y_log:
                        positive_y = y[y > 0]
                        if positive_y.size:
                            current_min = positive_y.min()
                            min_positive_y = current_min if min_positive_y is None else min(min_positive_y, current_min)

                # If base_var happens to be an alpha var but we plotted per-region files (unlikely), apply fixed alpha limits
                alpha_limits = {
                    'alpha_q': (-1.6, -0.2),
                    'alpha_deutron': (1.0, 2.0),
                    'alpha_p_final': (0.0, 1.0),
                    'alpha_p_initial': (1.0, 2.0)
                }
                if base_var in alpha_limits:
                    try:
                        left, right = alpha_limits[base_var]
                        ax.set_xlim(left, right)
                        ticks = np.arange(left, right + 1e-9, 0.1)
                        ax.set_xticks(ticks)
                    except Exception:
                        pass

            info = get_variable_info(base_var)
            ax.set_xlabel(info['label'])
            ax.set_ylabel('Total Weight' if not use_average_weight else 'Avg Weight')
            ax.grid(True, alpha=0.3)
            if y_log and any_plotted:
                ax.set_yscale('log')
                if min_positive_y is not None:
                    ax.set_ylim(bottom=min_positive_y * 0.8)
            if any_plotted:
                ax.legend(fontsize=9)
            else:
                ax.text(0.5, 0.5, f'No data for {base_var}', ha='center', va='center', transform=ax.transAxes)

        plt.suptitle(f'{group_name} grouped histograms {title_suffix}', fontsize=14)
        plt.tight_layout(rect=[0, 0, 1, 0.96])

        # Save
        safe_name = group_name.replace(' ', '_')
        out_dir = 'analysis_output/png_files/grouped_plots'
        os.makedirs(out_dir, exist_ok=True)
        suffix = '_avg' if use_average_weight else '_total'
        filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
        out_path = os.path.join(out_dir, f'plot_grouped_{safe_name}{mode_suffix}{suffix}{filter_suffix}.png')
        plt.savefig(out_path, dpi=300, bbox_inches='tight')
        # If this grouped plot contains any alpha variables, show it interactively
        alpha_keys = {'alpha_q', 'alpha_deutron', 'alpha_p_final', 'alpha_p_initial', 'alpha_sum'}
        try:
            if any(v in alpha_keys for v in var_list):
                plt.show()
        except Exception:
            pass
        plt.close()
        print(f'Saved grouped plot: {out_path}')

def plot_all_together_filtered(filtered_vars, use_average_weight=False, weight_filter_percentile=98.0):
    """Plot filtered histograms as subplots on one page (excludes grouped point variables)"""
    if not filtered_vars:
        print("No filtered variables to plot!")
        return

    n_vars = len(filtered_vars)
    cols = 4
    rows = (n_vars + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(16, 4*rows))
    if rows == 1:
        axes = [axes] if cols == 1 else axes
    else:
        axes = axes.flatten()

    plot_idx = 0
    for var_name in filtered_vars:
        x, y = load_histogram(var_name, use_average_weight, weight_filter_percentile)
        if x is None:
            continue
        info = get_variable_info(var_name)
        axes[plot_idx].plot(x, y, '-', color=info['color'], linewidth=2)
        axes[plot_idx].set_xlabel(info['label'], fontsize=12)
        if use_average_weight:
            axes[plot_idx].set_ylabel('Avg Weight', fontsize=12)
            plot_type = 'Average Weight'
        else:
            axes[plot_idx].set_ylabel('Total Weight', fontsize=12)
            plot_type = 'Total Weight'
        max_y = np.max(y)
        threshold = 0.01 * max_y
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
            axes[plot_idx].set_xlim(x_min - padding, x_max + padding)
        # Apply fixed alpha limits/ticks when requested
        alpha_limits = {
            'alpha_q': (-1.6, -0.2),
            'alpha_deutron': (1.0, 2.0),
            'alpha_p_final': (0.0, 1.0),
            'alpha_p_initial': (1.0, 2.0)
        }
        if var_name in alpha_limits:
            try:
                left, right = alpha_limits[var_name]
                axes[plot_idx].set_xlim(left, right)
                ticks = np.arange(left, right + 1e-9, 0.1)
                axes[plot_idx].set_xticks(ticks)
                try:
                    if axes[plot_idx].get_yscale() == 'linear':
                        axes[plot_idx].set_aspect('equal', adjustable='box')
                except Exception:
                    pass
            except Exception:
                pass
        axes[plot_idx].set_title(f'{info["label"]}', fontsize=14)
        axes[plot_idx].grid(True, alpha=0.3)
        plot_idx += 1

    for i in range(plot_idx, len(axes)):
        axes[i].set_visible(False)
    main_title = f'Individual 1D Histograms ({plot_type})'
    plt.suptitle(main_title, fontsize=18)
    plt.tight_layout()
    suffix = '_avg' if use_average_weight else '_total'
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    output_dir = "analysis_output/png_files/overview_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_all_histograms_individual{suffix}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    # If any alpha variables were included, show the overview interactively
    alpha_keys = {'alpha_q', 'alpha_deutron', 'alpha_p_final', 'alpha_p_initial', 'alpha_sum'}
    try:
        if any(v in alpha_keys for v in filtered_vars):
            plt.show()
    except Exception:
        pass
    plt.close()

def plot_all_together(use_average_weight=False, weight_filter_percentile=98.0):
    """Plot all histograms as subplots on one page"""
    # Discover available variables
    available_vars = discover_histogram_files()
    if not available_vars:
        print("No histogram files found!")
        return

    # Only include first and last xB_i and Q2_i regions, all others as usual
    xb_regions = [v for v in available_vars if v.startswith('xB_region')]
    q2_regions = [v for v in available_vars if v.startswith('Q2_region')]
    xb_selected = []
    q2_selected = []
    if xb_regions:
        xb_sorted = sorted(xb_regions, key=lambda x: int(x.split('xB_region')[1]))
        xb_selected = [xb_sorted[0], xb_sorted[-1]] if len(xb_sorted) > 1 else xb_sorted
    if q2_regions:
        q2_sorted = sorted(q2_regions, key=lambda x: int(x.split('Q2_region')[1]))
        q2_selected = [q2_sorted[0], q2_sorted[-1]] if len(q2_sorted) > 1 else q2_sorted

    # Filter out intermediate xB_i and Q2_i regions
    filtered_vars = []
    for v in available_vars:
        if v.startswith('xB_region') and v not in xb_selected:
            continue
        if v.startswith('Q2_region') and v not in q2_selected:
            continue
        filtered_vars.append(v)

    n_vars = len(filtered_vars)
    cols = 4
    rows = (n_vars + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(16, 4*rows))
    if rows == 1:
        axes = [axes] if cols == 1 else axes
    else:
        axes = axes.flatten()

    plot_idx = 0
    for var_name in filtered_vars:
        x, y = load_histogram(var_name, use_average_weight, weight_filter_percentile)
        if x is None:
            continue
        info = get_variable_info(var_name)
        axes[plot_idx].plot(x, y, '-', color=info['color'], linewidth=2)
        axes[plot_idx].set_xlabel(info['label'], fontsize=12)
        if use_average_weight:
            axes[plot_idx].set_ylabel('Avg Weight', fontsize=12)
            plot_type = 'Average Weight'
        else:
            axes[plot_idx].set_ylabel('Total Weight', fontsize=12)
            plot_type = 'Total Weight'
        max_y = np.max(y)
        threshold = 0.01 * max_y
        significant_mask = y > threshold
        if np.any(significant_mask):
            x_min, x_max = x[significant_mask].min(), x[significant_mask].max()
            x_range = x_max - x_min
            padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max)
            axes[plot_idx].set_xlim(x_min - padding, x_max + padding)
        # Apply fixed alpha limits/ticks when requested
        alpha_limits = {
            'alpha_q': (-1.6, -0.2),
            'alpha_deutron': (1.0, 2.0),
            'alpha_p_final': (0.0, 1.0),
            'alpha_p_initial': (1.0, 2.0)
        }
        if var_name in alpha_limits:
            try:
                left, right = alpha_limits[var_name]
                axes[plot_idx].set_xlim(left, right)
                ticks = np.arange(left, right + 1e-9, 0.1)
                axes[plot_idx].set_xticks(ticks)
            except Exception:
                pass
        axes[plot_idx].set_title(f'{info["label"]}', fontsize=14)
        axes[plot_idx].grid(True, alpha=0.3)
        plot_idx += 1

    for i in range(plot_idx, len(axes)):
        axes[i].set_visible(False)
    main_title = f'All 1D Histograms ({plot_type})'
    plt.suptitle(main_title, fontsize=18)
    plt.tight_layout()
    suffix = '_avg' if use_average_weight else '_total'
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    output_dir = "analysis_output/png_files/overview_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_all_histograms_1D{suffix}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    # If any alpha variables were included in available_vars, show the overview interactively
    alpha_keys = {'alpha_q', 'alpha_deutron', 'alpha_p_final', 'alpha_p_initial', 'alpha_sum'}
    try:
        if any(v in alpha_keys for v in available_vars):
            plt.show()
    except Exception:
        pass
    plt.close()

def main():
    """Main function to generate all plots"""
    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description='Plot 1D histograms from 3N SRC analysis',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python plot_1D_histograms.py              # Default: theta-based regions
    python plot_1D_histograms.py --xB         # Use xB-based regions  
    python plot_1D_histograms.py --mode xB    # Same as above
    python plot_1D_histograms.py --mode theta # Explicitly use theta-based regions
        """
    )
    parser.add_argument('--xB', action='store_true', 
                        help='Use xB-based regions (for comparison with 2N analysis)')
    parser.add_argument('--mode', choices=['theta', 'xB'], default='theta',
                        help='Region mode: "theta" for theta12-theta23 regions (default), "xB" for xB-based regions')
    parser.add_argument('--ylog', action='store_true',
                        help='Use logarithmic scale for y-axis')
    parser.add_argument('--linear-y', action='store_true',
                        help='Force linear y-axis, overriding defaults')
    args = parser.parse_args()
    
    # Determine region mode (--xB flag overrides --mode)
    region_mode = 'xB' if args.xB else args.mode
    # Default behavior: use log scale for both theta and xB modes; explicit flags override
    default_ylog = True
    y_log = args.ylog or (default_ylog and not args.linear_y)
    
    # Set global font sizes for matplotlib
    import matplotlib
    matplotlib.rcParams.update({
        'font.size': 12,           # Default font size
        'axes.titlesize': 16,      # Title font size
        'axes.labelsize': 14,      # Axis label font size
        'xtick.labelsize': 12,     # X-axis tick label font size
        'ytick.labelsize': 12,     # Y-axis tick label font size
        'legend.fontsize': 12,     # Legend font size
    })
    
    # Ensure output directories exist
    base_output_dir = ensure_output_directories()
    
    # Configuration: Set to True for average weight per event, False for total weight
    use_average_weight = False  # When true, displays total_bin_weight / bin_event_count
    
    # Weight filtering configuration: Filter out weights above this percentile
    # Set to 100 to disable filtering, or lower values (e.g., 99.5, 99, 95) to filter outliers
    weight_filter_percentile = 100.0 
    
    # Ratio plotting configuration: Set pairs of variables to calculate ratios
    # Format: [(var1, var2), ...] where ratio = var1 / var2
    # Examples:
    # ratio_pairs = [("xB star", "xB"), ("Q2 star", "Q2"), ("xB rocket", "xB rocket")]
    # ratio_pairs = [
    #     ("xB star", "xB"),
    #     ("Q2 star", "Q2"), 
    #     ("xB rocket", "xB"),
    #     ("Q2 rocket", "Q2")
    # ] 
    ratio_pairs = []
    
    # Multiple ratio plotting configuration: Plot multiple ratios on same figure
    # Format: [[(var1, var2), (var3, var4), ...], [...]] - each inner list becomes one plot
    multiple_ratio_groups = [
        # [(f"xB_region{i}", "xB") for i in range(7)],   # xB ratios for all regions
        # [(f"Q2_region{i}", "Q2") for i in range(7)]    # Q2 ratios for all regions
    ]
    
    # Discover available variables dynamically (useful for debugging)
    available_vars = discover_histogram_files()
    print("3N SRC Analysis Plotting Script")
    print("================================")
    print(f"Region mode: {region_mode}")
    print("Available variables:", available_vars)

    if not available_vars:
        print("No histogram files found! Please run the C++ program first.")
        return

    # Generate grouped plots with the selected region mode
    print(f"\nGenerating grouped plots using {region_mode}-based regions (y-log={'on' if y_log else 'off'})...")
    plot_grouped_histograms(use_average_weight=use_average_weight, 
                           weight_filter_percentile=weight_filter_percentile,
                           region_mode=region_mode,
                           y_log=y_log)
    print(f"Grouped plotting complete. Check analysis_output/png_files/grouped_plots/")

def plot_multiple_ratios(ratio_pairs, weight_filter_percentile=98.0, title=None):
    """Plot multiple ratio graphs together on the same figure
    
    Args:
        ratio_pairs: List of tuples [(var1, var2), ...] where ratio = var1 / var2
        weight_filter_percentile: Filter out weights above this percentile
        title: Optional custom title for the plot
        
    Example usage:
        plot_multiple_ratios([("xB star", "xB"), ("xB rocket", "xB")])
        plot_multiple_ratios([("Q2 star", "Q2"), ("Q2 rocket", "Q2")], title="Q2 Comparisons")
    """
    if not ratio_pairs:
        print("No ratio pairs provided")
        return
    
    # Use a better gradient for multiple ratios
    import matplotlib.cm as cm
    import matplotlib.colors as mcolors
    n_curves = len(ratio_pairs)
    cmap = cm.get_cmap('plasma')  # plasma, inferno, turbo, or rainbow are good alternatives to viridis
    colors = [cmap(i / max(n_curves - 1, 1)) for i in range(n_curves)]

    plt.figure(figsize=(10, 6))

    # Store x-axis limits for consistent plotting
    all_x_mins, all_x_maxs = [], []

    for i, (var1_name, var2_name) in enumerate(ratio_pairs):
        # Load both histograms (always use total weight for ratios)
        x1, y1 = load_histogram(var1_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
        x2, y2 = load_histogram(var2_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)

        if x1 is None or x2 is None:
            print(f"Error: Could not load histograms for {var1_name} and/or {var2_name}")
            continue

        # Check if the histograms have the same binning
        if len(x1) != len(x2) or not np.allclose(x1, x2, rtol=1e-10):
            print(f"Warning: {var1_name} and {var2_name} have different binning.")
            try:
                from scipy.interpolate import interp1d
                print("Attempting interpolation using scipy...")
                # Interpolate y2 to match x1 binning
                f = interp1d(x2, y2, kind='linear', bounds_error=False, fill_value=0)
                y2_interp = f(x1)
                x_common = x1
                y1_common = y1
                y2_common = y2_interp
            except ImportError:
                print("Scipy not available. Using simple resampling (may be less accurate).")
                # Simple fallback: use the variable with fewer bins as the common binning
                if len(x1) <= len(x2):
                    x_common = x1
                    y1_common = y1
                    y2_common = np.interp(x1, x2, y2)
                else:
                    x_common = x2
                    y2_common = y2
                    y1_common = np.interp(x2, x1, y1)
        else:
            x_common = x1
            y1_common = y1
            y2_common = y2

        # Calculate ratio, avoiding division by zero
        ratio = np.divide(y1_common, y2_common, out=np.zeros_like(y1_common), where=y2_common!=0)

        # Plot the ratio with gradient color
        color = colors[i]
        label = f'{var1_name} / {var2_name}'
        plt.plot(x_common, ratio, '-', color=color, linewidth=2, label=label)

        # Collect x-axis limits for consistent plotting
        max_combined = np.max([np.max(y1_common), np.max(y2_common)])
        threshold = 0.01 * max_combined
        significant_mask = (y1_common > threshold) | (y2_common > threshold)
        if np.any(significant_mask):
            x_min, x_max = x_common[significant_mask].min(), x_common[significant_mask].max()
            all_x_mins.append(x_min)
            all_x_maxs.append(x_max)
    
    # Set consistent x-axis limits across all ratios
    if all_x_mins and all_x_maxs:
        x_min_global = min(all_x_mins)
        x_max_global = max(all_x_maxs)
        x_range = x_max_global - x_min_global
        padding = 0.05 * x_range if x_range > 0 else 0.1 * abs(x_max_global)
        plt.xlim(x_min_global - padding, x_max_global + padding)
    
    # Get variable info for x-axis label (use first ratio pair)
    if ratio_pairs:
        info1 = get_variable_info(ratio_pairs[0][0])
        plt.xlabel(info1['label'], fontsize=14)
    
    plt.ylabel('Ratio', fontsize=14)
    
    # Set title
    if title:
        plot_title = title
    else:
        if len(ratio_pairs) == 1:
            plot_title = f'Ratio: {ratio_pairs[0][0]} / {ratio_pairs[0][1]}'
        else:
            plot_title = 'Multiple Ratio Comparison'
    
    filter_note = " (filtered)" if weight_filter_percentile < 100 else ""
    plt.title(f'{plot_title}{filter_note}', fontsize=16)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    
    # Save the plot
    filter_suffix = f'_f{weight_filter_percentile}' if weight_filter_percentile < 100 else ''
    # Create filename from ratio pairs with safe characters
    ratio_names = '_'.join([f"{r[0].replace(' ', '_').replace('.', '')}_over_{r[1].replace(' ', '_').replace('.', '')}" for r in ratio_pairs])
    output_dir = "analysis_output/png_files/ratio_plots"
    os.makedirs(output_dir, exist_ok=True)
    plt.savefig(f'{output_dir}/plot_multiple_ratios_{ratio_names}{filter_suffix}.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # Print statistics for each ratio
    print(f"\nStatistics for multiple ratios:")
    for var1_name, var2_name in ratio_pairs:
        x1, y1 = load_histogram(var1_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
        x2, y2 = load_histogram(var2_name, use_average_weight=False, weight_filter_percentile=weight_filter_percentile)
        
        if x1 is not None and x2 is not None:
            # Recalculate ratio for statistics (same logic as above)
            if len(x1) != len(x2) or not np.allclose(x1, x2, rtol=1e-10):
                if len(x1) <= len(x2):
                    y2_common = np.interp(x1, x2, y2)
                    y1_common = y1
                else:
                    y1_common = np.interp(x2, x1, y1)
                    y2_common = y2
            else:
                y1_common = y1
                y2_common = y2
            
            ratio = np.divide(y1_common, y2_common, out=np.zeros_like(y1_common), where=y2_common!=0)
            valid_ratio_mask = (y2_common != 0) & np.isfinite(ratio)
            
            if np.any(valid_ratio_mask):
                valid_ratios = ratio[valid_ratio_mask]
                print(f"  {var1_name} / {var2_name}:")
                print(f"    Mean: {np.mean(valid_ratios):.4f}, Median: {np.median(valid_ratios):.4f}")
                print(f"    Min: {np.min(valid_ratios):.4f}, Max: {np.max(valid_ratios):.4f}")

def plot_custom_ratio(var1_name, var2_name, weight_filter_percentile=100.0):
    """Convenience function to plot a custom ratio between any two variables
    
    Args:
        var1_name: First variable name (numerator)
        var2_name: Second variable name (denominator)  
        weight_filter_percentile: Filter out weights above this percentile
        
    Example usage:
        plot_custom_ratio("xB star", "xB")
        plot_custom_ratio("Q2 star", "Q2", weight_filter_percentile=95.0)
    """
    print(f"Plotting ratio: {var1_name} / {var2_name}")
    plot_ratio(var1_name, var2_name, weight_filter_percentile)

if __name__ == "__main__":
    main()
